# infra-repo/argocd-apps/krakend/krakend-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: krakend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ucanbaklava-cicd/infrastructure.git # Or HTTPS URL
    path: apps/krakend # Path to the manifests within the repo
    targetRevision: HEAD # Or main branch
  destination:
    server: https://kubernetes.default.svc
    namespace: krakend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true